apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-webapp
  namespace: demo-app
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: demo-webapp.localtest.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-webapp
            port:
              number: 80
