apiVersion: v1
kind: Service
metadata:
  name: demo-webapp
  namespace: demo-app
spec:
  # type: LoadBalancer
  type: ClusterIP
  selector:
    app: demo-webapp
  ports:
    - port: 80
      targetPort: 5000
